### ISSUE TITLE
EOL of v1.0

### ISSUE THREAD

**Issue by canihavesomecoffee** [Moinax/TvDb#41]
Hi Moinax,

I really love your library for theTVDb API, and it saddens me that it'll cease working in about 6 months time (https://forums.thetvdb.com/viewtopic.php?f=3&t=36557).

Are there any plans to update the library to work with v2, or do you have any recommendations?

**Comment by Moinax** [comment]
Hi @canihavesomecoffee 

A few month ago I was thinking of implementing the v2, but I discovered that there were already multiple implementations on github, like this one which seems pretty good https://github.com/adrenth/thetvdb2

I wrote the v1 because I couldn't find any decent client at that time, but this time the client I mentioned above seems well written.

I didn't had time to test it, so let me know if you see any problems using it, because, thanks to you, I know that I have 6 month to refactor http://www.nextepisode.tv with the new API. I didn't receive any alert (mail or so) to warn me about this, so thank you.

**Comment by canihavesomecoffee** [comment]
You're welcome :)

I think it's a bit difficult for the admins of theTVDb to send out emails, and they might assume developers visit their forums every now and then...

That said, I did see that library you mention, but I'm not completely happy with the looks and style of that one, and I'm considering of implementing one myself... Given that I currently use your awesome library I thought I'd ask first before possibly starting duplicate work. If I manage to finish something I'll also keep you updated, so maybe you could use mine then.

**Comment by canihavesomecoffee** [comment]
Hey @Moinax,

It looks like they postponed the sunset for an undefined amount of time, but in the meanwhile I also (finally!) finished my own library: https://github.com/canihavesomecoffee/theTVDbAPI/.

**Comment by Moinax** [comment]
Hi @canihavesomecoffee thank you for your update. 

That's really cool you created your own client. Was it long to update your project with your new API client ?

**Comment by canihavesomecoffee** [comment]
I had to migrate a couple of converter methods (which were forming a bridge between the object you returned and the internal classes of the project that used it), and then migrate some calls, that was pretty easy to do.

The biggest issue I encountered was the change in the returned non-English language results... The project is a Dutch website, so preferably everything should be in Dutch. With the old API, whenever you requested in a certain language, you'd get English as fallback, which is ideal for that purpose. With the new API however, you get null values. That's the reason I added a MultiLanguage fallback mechanism in my implementation...

I also spent quite some time to rewrite my update mechanism, but that's more because the initial version was buggy with cyclic updates (S01E01 to S01E02 and S01E02 to S01E01 for example).

So all in all, if you are just after English results (or don't care if things are missing), then the update should be reasonably easy.
